### ISSUE TITLE
Sometimes Map Doesn't Appear Mobile WebView

### ISSUE THREAD

**Issue by anileger** [pubgsh/api#7]
When I check the game 2d replay in my Android device (Sony Xperia XZ Premium), sometimes map image cannot load. Circles representing users works well.

![SnapShot20200203T235648](https://user-images.githubusercontent.com/5994548/73690575-b535a880-46e1-11ea-8c67-364f979f770a.jpg)

The screenshot has taken from [https://pubg.sh/Mithrain/steam/044ff6c7-4f5f-4ef1-8dca-d4cec592ca63](this URL)

**Comment by apazzolini** [comment]
I'm not going to fix this. I don't have any android devices, and I don't really play this game anymore. I'll accept a PR for it though if you want to fix it.
